### ISSUE TITLE
end of interview tends to ramble

### ISSUE THREAD

**Issue by scalar27** [DrewThomasson/doc2interview#2]
Not sure how you might address this, but the last several back and forths between the interviewer and interviewee tend to ramble and are somewhat repetitive.  Maybe a bigger model would do better, but I'm wondering if there might be something else you might tweak.

**Comment by DrewThomasson** [comment]
Hm, yeah your right honestly,

We could try having it use larger models like llama 3.1

Or doing further prompt engineering,



It is hard to keep it on track

**Comment by DrewThomasson** [comment]
If you want to try messing with it on your end you should just be able to edit the 

'Def generate_prompt' function to modify the prompt,


Or edit the

'Def run_ollama' function to use " llama3.1" or another model instead of "phi3.5"

You'll have to run "ollama pull llama3.1" to have Ollama download it or any other models listed on ollama's site

**Comment by scalar27** [comment]
Will play with this and report back!

**Comment by DrewThomasson** [comment]
Thinking about adding support for a faster Text To Speech engine.

Specifically styletts2

Free Interactive Demo : https://huggingface.co/spaces/styletts2/styletts2

what are your thoughts?

🤔

-As you can see its less emotional and natural sounding, but it is much faster

I wouldn't be taking away the current TTS engine, just giving the extra option to use this faster one.

**Comment by scalar27** [comment]
Sure, that would be nice.  I've played a bit with styetts2.  I would say for an application like yours the speed is not as critical as in a streaming application, so actually I prefer the higher quality voices.

**Comment by DrewThomasson** [comment]
Noted, thanks for the feedback! I'll just have it stay with the current XTTS model then.

:)

**Comment by DrewThomasson** [comment]
I might later try fixing the end ramblings by having the first output passed into the LLM again but this time just asking it to clean the first output up and remove any ramblings. 

That could potentially work

🤔

**Comment by DrewThomasson** [comment]
implemented on test branch

you can check it out by going to the doc2interview folder on your computer 

and running:

git checkout DrewThomasson-patch-1



you can go back to the main with

git checkout main



It seems better in my tests so far but ill have to use it a bunch to know for sure

**Comment by DrewThomasson** [comment]
### Here's an example of one of my tests on it giving it a script that rambles.

# 🤔


### Original ramble output from gpt4o as a test case:

Interviewer: Good day, Andrew Cunningham! We understand that you've delved into Microsoft’s Control Panel history and its potential future direction with new operating systems like Windows 10 and beyond. Can we explore this further? Thanks for joining us today.

Andrew: Absolutely! The Control Panel has been a core part of the Windows experience since Windows NT 4 in 1996. It's fascinating to see how it's evolved over the decades.

Interviewer: Definitely. It's played a key role, allowing users to manage system settings through applets – from hardware configurations to network connections.

Andrew: Exactly! Anyone who's spent time on a PC has probably interacted with it, adjusting display settings or changing the system time.

Interviewer: Microsoft is now phasing out these traditional panels in favor of the Settings app. What are your thoughts on this shift?

Andrew: It's a natural progression. While some Control Panel elements remain in updates like 24H2, Microsoft is clearly moving towards a more modern, touchscreen-friendly interface.

Interviewer: Some users may feel nostalgic about the old design, like the glassy look from Vista. How does this shift affect the overall design language of Windows?

Andrew: It’s significant, but as technology changes, especially with touchscreens becoming more common, it makes sense to modernize the interface.

Interviewer: In summary, Microsoft seems to be balancing modern interfaces with some legacy features. Any final thoughts?

Andrew: Well, you know, it’s always challenging when something so fundamental to our daily tech interactions changes, right? I mean, think about it—there are people out there who have been using the Control Panel for decades, and now suddenly they’re expected to adapt to something completely new. It’s like when your favorite coffee shop changes their menu. You think, "Why mess with a good thing?" But then again, progress is inevitable. Microsoft has always been good about balancing the old with the new, so I think they’ll handle it. And speaking of changes, have you noticed how coffee shops are starting to introduce all these non-dairy milk options? I tried oat milk the other day, and it was actually pretty good. Though, I still don’t understand the appeal of almond milk—it just tastes too watery for me, you know?

Interviewer: Oh, totally! I’ve had that exact same thought! Almond milk has this weird aftertaste, doesn't it? I’m more of a soy milk person, but oat milk has been growing on me, too. And speaking of weird trends, have you seen how every store now has those plant-based burgers? I had one the other day, and honestly, I couldn’t tell the difference. It's crazy how far we've come. But back to your point on Microsoft—like plant-based meat, these changes to Windows might seem drastic at first, but I think eventually they’ll be so normalized, no one will remember the old ways. But yeah, I do wonder if people will ever stop asking for regular milk... kind of like how some users might never stop asking for the classic Control Panel, right?

Andrew: Exactly! It’s like, no matter how many oat milk lattes or plant-based burgers you offer, there will always be that one person who wants the old thing, the original. It’s just human nature, I guess. People like what they’re used to. And honestly, I wonder how many of us will ever get truly used to all these new things. Like, what’s next? Soy-based pizza? Actually, wait—I think I’ve seen that somewhere! And that’s exactly what Microsoft is doing—phasing out the Control Panel one small update at a time, and eventually, it’ll be as normal as seeing a soy burger on the menu. It’s kind of funny when you think about it. Anyway, I’m glad we could chat about this today, and about the random rise of plant-based everything! Catch you next time!

Interviewer: Absolutely! Who knew we'd end up discussing oat milk and soy pizza while talking about Microsoft? Always a pleasure, Andrew! Until next time!





### Phase 2 output attempting to make it less ramble with phi3.5:


Interviewer: Good day, Andrew Cunningham! We understand that you've delved into 
Microsoft’s Control Panel history and its potential future direction with new 
operating systems like Windows 10 and beyond. Can we explore this further? Thanks 
for joining us today.

Andrew: Absolutely! The Control Panel has been a core part of the Windows experience 
since Windows NT 4 in 1996, showcasing its evolution over decades with various 
design iterations to adapt user needs and technology advancements.

Interv0rwer: Definitely significant as it was essential for system settings 
management through applets covering a wide range of configurations from hardware 
adjustments to network connections which are now seen less frequently in modern 
interfaces but remain historically important within the Windows ecosystem's 
contextual design evolution.

Andrew: Precisely, and its universality meant that almost everyone using PCs engaged 
with it at some point for basic system modifications such as display calibration or 
time synchronization – an interaction pattern which Microsoft is now streamlining in 
favor of a more integrated Settings app approach across different Windows versions 
while still retaining elements from legacy iterations like the 24Hr Service Pack 
updates.

Inter0wer: Indeed, this shift reflects not just changes within Microsoft’s design 
philosophy but also user behavior trends towards touch and mobile interfaces which 
dictate these modern alterations; it's a transition that echoes how Windows itself 
has matured from being heavily appliance-centric to more device agnostic. Given the 
company’s past emphasis on progressive usability enhancements while maintaining 
comfort zones, this change appears as an extension of their narrative in design 
language adaptation over time rather than a break with tradition—and is indicative 
that Microsoft has consistently taken strides towards intuitiveness and 
accessibility without completely discarding the roots from where it originated.

Andrew: Agreed; Windows’ approach to these transitions seems deeply rooted within 
its history, ensuring users' adaptability while embracing a future-ready interface 
that aligns with contemporary user interaction models yet respects and retains 
familiarity for those who grew up in the era of legacy systems.

**Comment by DrewThomasson** [comment]
Was Merged to main,

Now it's in the official main version cause it seemed to work well

**Comment by DrewThomasson** [comment]
Closing cause I guess it's fixed rn hopefully, can be reopened if not lol
